spring:
  data:
    mongodb:
      database: master
      password: rootpass
      username: rootuser
      host: localhost
      port: 27017
      authentication-database: admin

server:
  servlet:
    context-path: /master



