spring:
  profiles:
    active: @active@
  data:
    mongodb:
      authentication-database: admin
      uri: @uri.mongo@

server:
  servlet:
    context-path: @context@

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus


